### ISSUE TITLE
マッシュアップ用のスライドを作る

### ISSUE THREAD

**Issue by okamuroshogo** [okamuroshogo/auto_matching#20]
https://docs.google.com/presentation/d/1RIcjS9vL6ScvDpl55X-sjKLua9-WwyEVfxj3dYYBD6s/edit#slide=id.p

**Comment by skinnybrian** [comment]
これもベースできてMA2017 1st Stageでの発表も完了。
ブラッシュアップ&福岡ビジコンに向けてまた加筆修正する必要はあり。一旦クローズで

https://drive.google.com/file/d/1SHtes7a8izEo-rlQvMJhOlIcf6RJGlUn/view?usp=sharing
https://www.slideshare.net/ssuserf93625/kamatte
